version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copilot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - insight-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/copilot
    networks:
      - insight-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # App port
      #- "9229:9229" # Debug port
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - pnpm-store:/pnpm
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - SERVER_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      #- NODE_OPTIONS=--inspect=0.0.0.0:9229
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - insight-network

networks:
  insight-network:
    driver: bridge

volumes:
  pnpm-store:
  pgdata:
